language: node_js
node_js: 
  - 16.15.1

cache: npm

install:
  - npm install

script:
  - npm run test
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: gh-pages
